name: Run Go Telemetry API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Newman
      run: npm install -g newman

    - name: Start Go Telemetry Server
      run: |
        go run main.go &
        sleep 5

    - name: Run Newman Tests
      run: |
        newman run postman/go-telemetry.postman_collection.json \
          --environment postman/go-telemetry.postman_environment.json \
          --reporters cli,json \
          --reporter-json-export newman-report.json
